# 服务端口
server.port=8080
server.error.include-message=always
server.tomcat.uri-encoding=UTF-8
logging.level.org.springframework.web=DEBUG
# MySQL数据源配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-cn-4224vvb7t0001vlo.rwlb.rds.aliyuncs.com:3306/jiachangcai?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=JiaChangCai
spring.datasource.password=Root+123
# Mapper日志打印
logging.level.com.wsc.mapper=debug
# MyBatis映射文件路径
mybatis.mapper-locations=classpath:module/**/mapper/*.xml
# 实体类别名包（自行填写包路径）
mybatis.type-aliases-package=com.zzx.jiachangcai.module.*.entity
# 使用AI大模型对话解除下方所有注释
spring.ai.openai.api-key=sk-bdb0b94c5ee44bb6963bc3b02d927ddf
spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-chat
spring.ai.openai.chat.options.temperature=0.3
spring.threads.virtual.enabled=true
# 邮箱验证码发送配置（QQ邮箱SMTP，可发往任意邮箱）
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2849629703@qq.com
spring.mail.password=xyzagrjueadzddfa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true